env:
  LEIN_ROOT: "true"
  DTLV_ARCH: aarch64
  GITHUB_TOKEN: ENCRYPTED[!41f1e85b6e586455cca18744e840eb478625b1e76bdf38741704b504929b3115f541f73101393835ca625e2e9db295a2!]

task:
  name: Linux ARM64 Build
  arm_container:
    image: ubuntu:latest
    memory: 8G
  # only_if: $CIRRUS_TAG != ''
  only_if: "changesInclude('.cirrus.yml', 'src/*', 'script/*')"
  env:
    DTLV_OS: linux
  script: |

    DEBIAN_FRONTEND=noninteractive apt-get update -y
    DEBIAN_FRONTEND=noninteractive apt-get install -y curl git wget tar zlib1g-dev build-essential locales p7zip-full g++-12 gcc-12

    locale-gen en_US en_US.UTF-8
    dpkg-reconfigure locales

    script/install-graalvm

    export GRAALVM_HOME="$(cd graalvm-jdk && pwd)"
    export JAVA_HOME=$GRAALVM_HOME
    export PATH=$GRAALVM_HOME/bin:$PATH

    export LANGUAGE=en_US.UTF-8
    export LC_ALL=en_US.UTF-8
    export LANG=en_US.UTF-8
    export LC_CTYPE=en_US.UTF-8

    curl -O https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    chmod a+x lein
    mv lein /usr/local/bin/

    export JAVA_OPTS="-Xmx8g -XX:+UseG1GC"
    lein run

    script/compile-native-linux

    ./dtlv-test0

    export DTLV_ARCHIVE="dtlv-${CIRRUS_TAG}-ubuntu-latest-aarch64.zip"
    export DTLV_TAG="${CIRRUS_TAG}"

    7z a -tzip "$DTLV_ARCHIVE" dtlv

    curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
    chmod +x install
    ./install

    bb --config .build/bb.edn release-artifact

task:
  name: MacOS ARM64 Build
  macos_instance:
    image: ghcr.io/cirruslabs/macos-runner:sonoma
  # only_if: $CIRRUS_TAG != ''
  only_if: "changesInclude('.cirrus.yml', 'src/*', 'script/*')"
  env:
    DTLV_OS: macos
  script: |

    script/install-graalvm

    export GRAALVM_HOME="$(cd graalvm-jdk/Contents/Home && pwd)"
    export JAVA_HOME=$GRAALVM_HOME
    export PATH=$GRAALVM_HOME/bin:$PATH

    brew install leiningen libomp llvm
    lein run

    script/compile-native

    ./dtlv-test0

    brew install p7zip

    export DTLV_ARCHIVE="dtlv-${CIRRUS_TAG}-macos-latest-aarch64.zip"
    export DTLV_TAG="${CIRRUS_TAG}"

    7z a -tzip "$DTLV_ARCHIVE" dtlv

    brew install borkdude/brew/babashka

    bb --config .build/bb.edn release-artifact
