env:
  LEIN_SNAPSHOTS_IN_RELEASE: true
  LEIN_ROOT: "true"
  GRAALVM_VERSION: "22.3.1"
  DTLV_ARCH: aarch64
  GITHUB_TOKEN: ENCRYPTED[d7c52b8e3868deeded4a79eceb563b167781f0a85b8cade35bddcf2b00d41c823fe64e6eac5d750b917ec52dd8783b33]

task:
  name: Linux ARM64 Build
  arm_container:
    image: ubuntu:latest
    memory: 8G
  only_if: $CIRRUS_TAG != ''
  env:
    DTLV_PLATFORM: linux
  script: |

    apt-get update
    apt-get install -y curl git wget tar openjdk-11-jre-headless zlib1g-dev build-essential
    
    curl -O https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
    chmod a+x lein
    mv lein /usr/local/bin/

    export JAVA_OPTS="-Xmx8g -XX:+UseG1GC"
    lein run

    cd native
    script/install-graalvm

    export GRAALVM_HOME=$(pwd)/graalvm-ce-java11-${GRAALVM_VERSION}
    export JAVA_HOME=$GRAALVM_HOME
    export PATH=$GRAALVM_HOME/bin:$PATH
    export STATIC_EXCEPT_LIBC=true

    script/compile

    cd ..
    native/dtlv-test0

    cd native

    apt-get install -y p7zip-full

    export DTLV_ARCHIVE="dtlv-${CIRRUS_TAG}-ubuntu-latest-aarch64.zip"
    export DTLV_TAG="${CIRRUS_TAG}"

    7z a -tzip "$DTLV_ARCHIVE" dtlv

    curl -sLO https://raw.githubusercontent.com/babashka/babashka/master/install
    chmod +x install
    ./install

    bb --config ../.build/bb.edn release-artifact


task:
  name: macOS ARM64 Build
  macos_instance:
    image: ghcr.io/cirruslabs/macos-monterey-base:latest
  only_if: $CIRRUS_TAG != ''
  # only_if: "changesInclude('.cirrus.yml', 'src/*', 'native/script/*')"
  env:
    DTLV_PLATFORM: macos
  script: |

    brew install leiningen
    lein run

    cd native
    script/install-graalvm

    export GRAALVM_HOME=$(pwd)/graalvm-ce-java11-${GRAALVM_VERSION}/Contents/Home
    export JAVA_HOME=$GRAALVM_HOME
    export PATH=$GRAALVM_HOME/bin:$PATH

    script/compile

    cd ..
    native/dtlv-test0

    cd native

    brew install p7zip

    export DTLV_ARCHIVE="dtlv-${CIRRUS_TAG}-macos-latest-aarch64.zip"
    export DTLV_TAG="${CIRRUS_TAG}"

    7z a -tzip "$DTLV_ARCHIVE" dtlv

    brew install borkdude/brew/babashka

    bb --config ../.build/bb.edn release-artifact
