#!/bin/bash

set -eou pipefail

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

export JAVA_HOME=$GRAALVM_HOME
export PATH=$GRAALVM_HOME/bin:$PATH

echo $JAVA_HOME

args_test1=(
    "--verbose"
    "-jar" "target/test1.uberjar.jar"
    "-H:Name=dtlv-test1"
)

lein clean
lein with-profile test1-uberjar uberjar

"$GRAALVM_HOME/bin/native-image" "${args_test1[@]}"
