#!/bin/bash

set -eou pipefail

app_name=dtlv

test0_name=dtlv-test0
test1_name=dtlv-test1
test2_name=dtlv-test2

if [ -z "$GRAALVM_HOME" ]; then
    echo "Please set GRAALVM_HOME"
    exit 1
fi

export JAVA_HOME=$GRAALVM_HOME
export PATH=$GRAALVM_HOME/bin:$PATH

MAIN_JAR="target/main.uberjar.jar"

TEST0_JAR="target/test0.uberjar.jar"
TEST1_JAR="target/test1.uberjar.jar"
TEST2_JAR="target/test2.uberjar.jar"

lein clean
lein with-profile native-uberjar uberjar

"$GRAALVM_HOME/bin/native-image" \
  --verbose \
  --add-opens "org.graalvm.nativeimage.builder/com.oracle.svm.core=ALL-UNNAMED" \
  --add-opens "org.graalvm.nativeimage.builder/com.oracle.svm.core.option=ALL-UNNAMED" \
  --add-opens "org.graalvm.nativeimage.builder/com.oracle.svm.core.c=ALL-UNNAMED" \
  -jar "$MAIN_JAR" ${app_name}

lein clean
lein with-profile test0-uberjar uberjar

"$GRAALVM_HOME/bin/native-image" -R:MaxHeapSize=5g -jar "$TEST0_JAR" ${test0_name}

lein clean
lein with-profile test1-uberjar uberjar

"$GRAALVM_HOME/bin/native-image" -R:MaxHeapSize=5g -jar "$TEST1_JAR" ${test1_name}

lein clean
lein with-profile test2-uberjar uberjar

"$GRAALVM_HOME/bin/native-image" \
  --verbose \
  --add-opens "org.graalvm.nativeimage.builder/com.oracle.svm.core=ALL-UNNAMED" \
  --add-opens "org.graalvm.nativeimage.builder/com.oracle.svm.core.option=ALL-UNNAMED" \
  --add-opens "org.graalvm.nativeimage.builder/com.oracle.svm.core.c=ALL-UNNAMED" \
  -R:MaxHeapSize=5g  \
  -jar "$TEST2_JAR" ${test2_name}
