#!/bin/bash

set -eou pipefail

app_name=dtlv

export JAVA_HOME=$GRAALVM_HOME
export PATH=$GRAALVM_HOME\bin:$PATH

PWD=`pwd`

MAIN_JAR="${PWD}\target\main.uberjar.jar"
CPATH="${PWD}\src\c"

"$GRAALVM_HOME\bin\native-image.cmd" \
    -H:Name=${app_name} \
    -H:+ReportExceptionStackTraces \
    -H:ConfigurationFileDirectories=config \
    -J-Dclojure.spec.skip-macros=true \
    -J-Dclojure.compiler.direct-linking=true \
    -H:Log=registerResource:verbose \
    -H:+PrintClassInitialization \
    -H:CLibraryPath="$CPATH" \
    --initialize-at-build-time \
    --report-unsupported-elements-at-runtime \
    --allow-incomplete-classpath \
    --verbose \
    --no-fallback \
    --no-server \
    "-J-Xmx8g" \
    --native-image-info \
    -jar "$MAIN_JAR" \
    ${app_name}
