#!/usr/bin/env bash

set -euo pipefail

apt-get update -y && apt-get install musl-tools -y

ZLIB_VERSION="1.2.13"
ZLIB_SHA256="b3a24de97a8fdbc835b9833169501030b8977031bcb54b3b3ac13740f846ab30"

# stable archive path
curl -O -sL --fail --show-error "https://zlib.net/fossils/zlib-${ZLIB_VERSION}.tar.gz"

echo "${ZLIB_SHA256} zlib-${ZLIB_VERSION}.tar.gz" | sha256sum --check
tar xf "zlib-${ZLIB_VERSION}.tar.gz"

cd "zlib-${ZLIB_VERSION}"
CC=musl-gcc ./configure --static --prefix="/usr/local"
make CC=musl-gcc
make install
cd ..

# Install libz.a in the correct place so ldd can find it
install -Dm644 "/usr/local/lib/libz.a" "/usr/lib/x86_64-linux-musl/libz.a"

if [ ! -f /usr/bin/x86_64-linux-musl-gcc ]
then
    ln -s /usr/bin/musl-gcc /usr/bin/x86_64-linux-musl-gcc
fi

# Get libstdc++.a from precompiled musl toolchain
wget http://more.musl.cc/11/x86_64-linux-musl/x86_64-linux-musl-native.tgz
tar xzf x86_64-linux-musl-native.tgz
cp x86_64-linux-musl-native/lib/libstdc++.a /usr/lib/x86_64-linux-musl/
